variables:
  TEST_BE_IMAGE: harbor.gyssteel.com/base_images/php-test:8.3
  TEST_FE_IMAGE: node:18-alpine

stages:
  - test
  - code-quality
  - build
  - approval
  - semver

include:
  - project: $DEPLOYMENT_PATH
    ref: main
    file:
      - unit-test.yaml
      - sonarqube.yaml
      - build.yaml
      - approval.yaml
      - semver.yaml
