variables:
  CI_REGISTRY: harbor.gyssteel.com

stages:
  - build
  - deploy

# ==========================================================
# PROD — BUILD STAGE (branch: main)
# ==========================================================

build_server:
  stage: build
  tags:
    -  CI-Shell 
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - server/**/*
  script:
    - docker build --cache-from -t $CI_REGISTRY/portalai/server:CI_COMMIT_BRANCH.$CI_COMMIT_SHA ./server .
    - docker push $CI_REGISTRY/portalai:CI_COMMIT_BRANCH.$CI_COMMIT_SHA 

build_client:
  stage: build
  tags:
    -  CI-Shell
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - client/**/*
  script:
    - docker build --cache-from -t $CI_REGISTRY/portalai/client:CI_COMMIT_BRANCH.$CI_COMMIT_SHA ./client .
    - docker push $CI_REGISTRY/portalai:CI_COMMIT_BRANCH.$CI_COMMIT_SHA