stages:
  - build
  - deploy

variables:
  IMAGE_CLIENT: harbor.gyssteel.com/portalai/client
  IMAGE_SERVER: harbor.gyssteel.com/portalai/server

build_client:
  stage: build
  tags:
    - CI-Shell
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip-build\]/
      when: never
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - client/**/*
  script:
    - >
      docker build
      -f client/Dockerfile
      -t $IMAGE_CLIENT:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA client/

    - docker push $IMAGE_CLIENT:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    - docker rmi $IMAGE_CLIENT:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

build_server:
  stage: build
  tags:
    - CI-Shell
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip-build\]/
      when: never
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - server/**/*
  script:
    - >
      docker build
      -f server/Dockerfile
      -t $IMAGE_SERVER:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA server/

    - docker push $IMAGE_SERVER:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    - docker rmi $IMAGE_SERVER:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

#DEPLOY#

deploy_client:
  stage: deploy
  tags:
    - gys-dev
  needs:
    - job: build_client
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - client/**/*
  script:
    - export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
    - export IMAGE_TAG=$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    - sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" client/deploy-client.yaml
    - kubectl apply -f client/deploy-client.yaml

deploy_server:
  stage: deploy
  tags:
    - gys-dev
  needs:
    - job: build_server
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - server/**/*
  script:
    - export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
    - export IMAGE_TAG=$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    - sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" server/deploy-dev.yaml
    - kubectl apply -f server/deploy-dev.yaml
