import ExcelJS from 'exceljs';
import path from 'path';

export default {
  async generateExcel({ sheetData, title, outputDir }) {
    const safeTitle = (title || "Spreadsheet").replace(/[^a-zA-Z0-9\s-]/g, "").replace(/\s+/g, "-").substring(0, 40);
    const filename = `GYS-${safeTitle}-${Date.now()}.xlsx`;
    const filepath = path.join(outputDir, filename);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'GYS Portal AI';
    workbook.created = new Date();

    if (!sheetData || !sheetData.sheets || sheetData.sheets.length === 0) {
      const sheet = workbook.addWorksheet('Sheet1');
      sheet.addRow(['No data generated by AI']);
    } else {
      for (const s of sheetData.sheets) {
        const sheet = workbook.addWorksheet(s.name || 'Data');
        
        // Add headers
        if (s.columns && s.columns.length > 0) {
          sheet.columns = s.columns.map(col => ({
            header: col,
            key: col,
            width: Math.max(15, Math.min(50, col.length * 1.5)) // Auto width estimate
          }));
          
          // Style headers
          sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
          sheet.getRow(1).fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FF064E3B' } // GYS Dark Green
          };
          sheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };
        }

        // Add rows
        if (s.rows && s.rows.length > 0) {
          s.rows.forEach(row => {
            // Handle both object and array representations
            if (Array.isArray(row)) {
              sheet.addRow(row);
            } else {
              sheet.addRow(row);
            }
          });
        }
        
        // Add borders to all populated cells
        sheet.eachRow((row, rowNumber) => {
          row.eachCell((cell) => {
            cell.border = {
              top: { style: 'thin' },
              left: { style: 'thin' },
              bottom: { style: 'thin' },
              right: { style: 'thin' }
            };
          });
        });
      }
    }

    await workbook.xlsx.writeFile(filepath);

    return {
      fileUrl: `/api/files/${filename}`,
      fileName: filename,
    };
  }
};
